import {StyleSheet} from 'react-native';
import {
  primaryColor,
  primaryFontLight,
  primaryFontMedium,
  primaryFontRegular,
  primaryFontSemiBold,
  secondaryColor,
} from '../../../../styles/main';

const styles = StyleSheet.create({
  containerContent: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '110%',
    backgroundColor: 'white',
  },
  content: {
    width: '75%',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  title: {
    fontSize: 24,
    fontFamily: primaryFontSemiBold,
    color: 'black',
    marginBottom: 10,
  },
  label: {
    fontSize: 16,
    fontFamily: primaryFontSemiBold,
    color: 'black',
    marginBottom: 5,
  },
  textCat: {
    fontSize: 16,
    fontFamily: primaryFontLight,
    color: 'black',
  },
  textArea: {
    height: 'auto',
    borderRadius: 10,
    backgroundColor: '#F7F8F9',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E8ECF4',
    paddingHorizontal: 20,
    padding: 20,
    textAlignVertical: 'top',
    marginBottom: 20,
    color: 'black',
    fontFamily: primaryFontMedium,
  },
  imageUpload: {
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  image: {
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
    aspectRatio: '180/150',
  },
  imageSelected: {
    width: '100%',
    height: 250,
    backgroundColor: 'transparent',
    padding: 0,
    margin: 0,
  },
  blockIcon: {
    width: 42,
    height: 42,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 50,
  },
  icon: {
    width: 20,
    height: 20,
  },
  categoryLabel: {
    color: 'black',
    fontFamily: primaryFontRegular,
  },
  blockImage: {
    width: '100%',
  },
  input: {
    width: '100%',
    height: 40,
    backgroundColor: '#E8ECF4',
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  blocCategory: {
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 50,
    paddingRight: 15,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 3.05,
    elevation: 10,
  },
  listCategories: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 20,
    marginTop: 20,
  },
  blocCategories: {
    marginTop: 20,
  },
  selectedCategory: {
    backgroundColor: primaryColor,
  },
  labelSelectedCategory: {
    color: 'white',
  },
  error: {
    color: 'red',
    textAlign: 'center',
    marginTop: 5,
    borderRadius: 10,
    fontFamily: primaryFontRegular,
  },
  blocButtonsImage: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    marginTop: 10,
    marginBottom: 50,
  },
  blockButtonAddImage: {
    width: '100%',
    height: 100,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E8ECF4',
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  buttonAddImage: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  buttonAddImageText: {
    textAlign: 'center',
    color: 'black',
    fontFamily: primaryFontMedium,
    fontSize: 14,
  },
});

export default styles;
